package nodeapi

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/netip"
	"net/url"
	"strings"
)

// Handler is the agent-side implementation the server dispatches to. Streaming
// operations receive a writer whose lines are forwarded to the hub live.
type Handler interface {
	Health() HealthResponse
	Install(ctx context.Context, req InstallRequest, log io.Writer) error
	ApplyCert(ctx context.Context, req CertRequest, log io.Writer) error
	Uninstall(ctx context.Context, req UninstallRequest, log io.Writer) error
	Subscription(format string) ([]byte, error)
}

// UpgradeHandler is implemented by agents that support in-overlay binary
// upgrades. It is optional so a hub can report a clear unsupported response
// when probing an older agent implementation.
type UpgradeHandler interface {
	Upgrade(ctx context.Context, req UpgradeRequest, log io.Writer) error
}

// CoreHandler is implemented by agents that support changing the local
// sing-box core to an exact hub-selected stable release.
type CoreHandler interface {
	ChangeCore(ctx context.Context, req CoreRequest, log io.Writer) error
}

// RelayHandler is implemented by agents that can front another node's traffic.
// Keeping it optional lets a newer Hub report an agent that predates relaying
// instead of failing an install with a routing error.
type RelayHandler interface {
	ApplyRelay(ctx context.Context, req RelayRequest, log io.Writer) error
}

// ProtocolStateHandler is implemented by agents that support full protocol
// editing. Keeping it optional lets a newer Hub diagnose an older Agent
// cleanly instead of changing the base lifecycle interface.
type ProtocolStateHandler interface {
	ProtocolState(context.Context) (ProtocolStateResponse, error)
}

// MonitorHandler is implemented by an agent that has an in-process monitor.
// The Server invokes it only with one of the fixed local monitor paths declared
// by MonitorEndpoint and strips the request query before dispatch.
type MonitorHandler interface {
	MonitorHandler() http.Handler
}

// TrafficUsageHandler is implemented by agents that support reading and
// replacing current-cycle traffic usage. It is separate from MonitorHandler so
// write requests can never be forwarded to the monitor's read-only HTTP mux.
type TrafficUsageHandler interface {
	TrafficUsage(context.Context) (TrafficUsage, error)
	SetTrafficUsage(context.Context, TrafficUsageRequest) (TrafficUsageUpdate, error)
}

// Server exposes Handler over HTTP, guarded by a bearer token.
type Server struct {
	Token   string
	Handler Handler
}

// Mux returns the routed HTTP handler.
func (s *Server) Mux() http.Handler {
	mux := http.NewServeMux()
	s.handle(mux, http.MethodGet, "/api/health", s.handleHealth)
	s.handle(mux, http.MethodGet, "/api/protocol-state", s.handleProtocolState)
	s.handle(mux, http.MethodPost, "/api/install", s.handleInstall)
	s.handle(mux, http.MethodPost, "/api/cert", s.handleCert)
	s.handle(mux, http.MethodPost, "/api/uninstall", s.handleUninstall)
	s.handle(mux, http.MethodPost, "/api/upgrade", s.handleUpgrade)
	s.handle(mux, http.MethodPost, "/api/core", s.handleCore)
	s.handle(mux, http.MethodPost, "/api/relay", s.handleRelay)
	s.handle(mux, http.MethodGet, "/api/subscription", s.handleSubscription)
	mux.HandleFunc("/api/monitor/usage", s.auth(s.handleTrafficUsage))
	for _, endpoint := range monitorEndpoints {
		apiPath, _, _ := endpoint.paths()
		s.handle(mux, http.MethodGet, apiPath, s.handleMonitor(endpoint))
	}
	return securityHeaders(mux)
}

func (s *Server) handle(mux *http.ServeMux, method, path string, next http.HandlerFunc) {
	mux.HandleFunc(path, s.auth(requireMethod(method, next)))
}

func requireMethod(method string, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != method {
			w.Header().Set("Allow", method)
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		next(w, r)
	}
}

// securityHeaders applies to successful responses and every error generated by
// the mux, including authentication failures, method errors, and 404s.
func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Content-Security-Policy", "default-src 'none'; frame-ancestors 'none'")
		w.Header().Set("Referrer-Policy", "no-referrer")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "DENY")
		next.ServeHTTP(w, r)
	})
}

// auth wraps a handler with constant-time bearer-token verification.
func (s *Server) auth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		values := r.Header.Values("Authorization")
		authorization := ""
		if len(values) == 1 {
			authorization = values[0]
		}
		const prefix = "Bearer "
		token := ""
		if strings.HasPrefix(authorization, prefix) {
			token = strings.TrimPrefix(authorization, prefix)
		}
		if s.Token == "" || token == "" || subtle.ConstantTimeCompare([]byte(token), []byte(s.Token)) != 1 {
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		next(w, r)
	}
}

func (s *Server) handleHealth(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, s.Handler.Health())
}

func (s *Server) handleProtocolState(w http.ResponseWriter, r *http.Request) {
	handler, ok := s.Handler.(ProtocolStateHandler)
	if !ok {
		http.Error(w, "protocol state is not supported by this agent", http.StatusNotImplemented)
		return
	}
	current, err := handler.ProtocolState(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, current)
}

func (s *Server) handleInstall(w http.ResponseWriter, r *http.Request) {
	var req InstallRequest
	if err := decodeJSON(w, r, &req, maxInstallRequestBody); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := ValidateInstallSingBoxVersion(req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	streamOperation(w, func(log io.Writer) error {
		return s.Handler.Install(r.Context(), req, log)
	})
}

func (s *Server) handleCert(w http.ResponseWriter, r *http.Request) {
	var req CertRequest
	if err := decodeJSON(w, r, &req, maxCertRequestBody); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	streamOperation(w, func(log io.Writer) error {
		return s.Handler.ApplyCert(r.Context(), req, log)
	})
}

func (s *Server) handleUninstall(w http.ResponseWriter, r *http.Request) {
	var req UninstallRequest
	if err := decodeJSON(w, r, &req, maxUninstallRequestBody); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	streamOperation(w, func(log io.Writer) error {
		return s.Handler.Uninstall(r.Context(), req, log)
	})
}

func (s *Server) handleUpgrade(w http.ResponseWriter, r *http.Request) {
	var req UpgradeRequest
	if err := decodeJSON(w, r, &req, maxUpgradeRequestBody); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := ValidateUpgradeRequest(req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	handler, ok := s.Handler.(UpgradeHandler)
	if !ok {
		http.Error(w, "agent upgrade is not supported", http.StatusNotImplemented)
		return
	}
	streamOperation(w, func(log io.Writer) error {
		return handler.Upgrade(r.Context(), req, log)
	})
}

func (s *Server) handleCore(w http.ResponseWriter, r *http.Request) {
	var req CoreRequest
	if err := decodeJSON(w, r, &req, maxCoreRequestBody); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := ValidateCoreRequest(req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	handler, ok := s.Handler.(CoreHandler)
	if !ok {
		http.Error(w, "sing-box core management is not supported", http.StatusNotImplemented)
		return
	}
	streamOperation(w, func(log io.Writer) error {
		return handler.ChangeCore(r.Context(), req, log)
	})
}

func (s *Server) handleRelay(w http.ResponseWriter, r *http.Request) {
	var req RelayRequest
	if err := decodeJSON(w, r, &req, maxRelayRequestBody); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := ValidateRelayRequest(req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	handler, ok := s.Handler.(RelayHandler)
	if !ok {
		http.Error(w, "relay forwarding is not supported by this agent", http.StatusNotImplemented)
		return
	}
	streamOperation(w, func(log io.Writer) error {
		return handler.ApplyRelay(r.Context(), req, log)
	})
}

func (s *Server) handleSubscription(w http.ResponseWriter, r *http.Request) {
	format := r.URL.Query().Get("format")
	body, err := s.Handler.Subscription(format)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	_, _ = w.Write(body)
}

func (s *Server) handleTrafficUsage(w http.ResponseWriter, r *http.Request) {
	handler, ok := s.Handler.(TrafficUsageHandler)
	if !ok {
		http.Error(w, "traffic usage management is not supported by this agent", http.StatusNotImplemented)
		return
	}
	switch r.Method {
	case http.MethodGet:
		usage, err := handler.TrafficUsage(r.Context())
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if err := ValidateTrafficUsage(usage); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		writeJSON(w, usage)
	case http.MethodPut:
		var wire struct {
			InBytes            *uint64 `json:"inBytes"`
			OutBytes           *uint64 `json:"outBytes"`
			ExpectedCycleStart *int64  `json:"expectedCycleStart"`
		}
		if err := decodeStrictJSON(w, r, &wire, maxTrafficUsageRequestBody); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if wire.InBytes == nil || wire.OutBytes == nil || wire.ExpectedCycleStart == nil {
			http.Error(w, "inBytes, outBytes, and expectedCycleStart are required", http.StatusBadRequest)
			return
		}
		req := TrafficUsageRequest{
			InBytes: *wire.InBytes, OutBytes: *wire.OutBytes,
			ExpectedCycleStart: *wire.ExpectedCycleStart,
		}
		if err := ValidateTrafficUsageRequest(req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		update, err := handler.SetTrafficUsage(r.Context(), req)
		if err != nil {
			status := http.StatusInternalServerError
			if IsTrafficCycleConflict(err) {
				status = http.StatusConflict
			}
			http.Error(w, err.Error(), status)
			return
		}
		if err := ValidateTrafficUsageUpdate(update); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if update.Applied.InBytes != req.InBytes || update.Applied.OutBytes != req.OutBytes ||
			update.Applied.CycleStart != req.ExpectedCycleStart {
			http.Error(w, "traffic usage handler returned a result that does not match the request", http.StatusInternalServerError)
			return
		}
		writeJSON(w, update)
	default:
		w.Header().Set("Allow", http.MethodGet+", "+http.MethodPut)
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (s *Server) handleMonitor(endpoint MonitorEndpoint) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		provider, ok := s.Handler.(MonitorHandler)
		if !ok {
			http.Error(w, "agent monitor is not supported", http.StatusNotImplemented)
			return
		}
		handler := provider.MonitorHandler()
		if handler == nil {
			http.Error(w, "agent monitor is not running", http.StatusServiceUnavailable)
			return
		}
		_, handlerPath, ok := endpoint.paths()
		if !ok {
			http.Error(w, "monitor endpoint not found", http.StatusNotFound)
			return
		}

		// Never pass a caller-controlled path or query to the monitor. In
		// particular, dropping `source` prevents its multi-source handler from
		// proxying to a URL stored in a remote snapshot.
		//
		// One endpoint drills into a single address, so it needs a parameter.
		// The address is parsed and written back out rather than forwarded, so
		// what reaches the monitor is still a value this process produced.
		query := ""
		if endpoint == MonitorIPDetail {
			address, err := netip.ParseAddr(strings.TrimSpace(r.URL.Query().Get("ip")))
			if err != nil {
				http.Error(w, "ip must be an IP address", http.StatusBadRequest)
				return
			}
			query = url.Values{"ip": []string{address.String()}}.Encode()
		}
		monitorRequest := r.Clone(r.Context())
		monitorRequest.Method = http.MethodGet
		monitorRequest.URL.Path = handlerPath
		monitorRequest.URL.RawPath = ""
		monitorRequest.URL.RawQuery = query
		monitorRequest.RequestURI = handlerPath
		monitorRequest.Header = r.Header.Clone()
		monitorRequest.Header.Del("Authorization")
		monitorRequest.Body = http.NoBody
		handler.ServeHTTP(w, monitorRequest)
	}
}

const (
	maxInstallRequestBody      int64 = 4 << 20
	maxCertRequestBody         int64 = 2 << 20
	maxUninstallRequestBody    int64 = 16 << 10
	maxCoreRequestBody         int64 = 4 << 10
	maxTrafficUsageRequestBody int64 = 4 << 10
	// A relay job is a handful of small records per landing node, and a hub
	// fronting a large fleet through one relay is still far inside this.
	maxRelayRequestBody int64 = 256 << 10
	// []byte expands by 4/3 when JSON/base64 encoded. Leave a small allowance
	// for field names and the version/digest strings.
	maxUpgradeRequestBody int64 = (MaxAgentBinarySize+2)/3*4 + 4096
)

// decodeJSON accepts exactly one JSON value, bounded before decoding. JSON
// whitespace after the value is permitted; a second value or any other
// trailing bytes are rejected.
func decodeJSON(w http.ResponseWriter, r *http.Request, dst any, maxBytes int64) error {
	return decodeJSONWithOptions(w, r, dst, maxBytes, false)
}

func decodeStrictJSON(w http.ResponseWriter, r *http.Request, dst any, maxBytes int64) error {
	return decodeJSONWithOptions(w, r, dst, maxBytes, true)
}

func decodeJSONWithOptions(w http.ResponseWriter, r *http.Request, dst any, maxBytes int64, strict bool) error {
	if r.Body == nil {
		return fmt.Errorf("request body is required")
	}
	r.Body = http.MaxBytesReader(w, r.Body, maxBytes)
	decoder := json.NewDecoder(r.Body)
	if strict {
		decoder.DisallowUnknownFields()
	}
	if err := decoder.Decode(dst); err != nil {
		return fmt.Errorf("decode JSON request: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return fmt.Errorf("request body must contain exactly one JSON value")
		}
		return fmt.Errorf("invalid data after JSON request: %w", err)
	}
	return nil
}

// streamOperation runs op, forwarding its log output to the client as it is
// produced, and finishes with a status sentinel line the client parses.
func streamOperation(w http.ResponseWriter, op func(log io.Writer) error) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	flusher, _ := w.(http.Flusher)
	lw := &lineFlushWriter{w: w, flusher: flusher}
	err := op(lw)
	if err != nil {
		fmt.Fprintf(w, "%s%s\n", errorSentinelPrefix, sanitizeLine(err.Error()))
	} else {
		fmt.Fprintf(w, "%s\n", doneSentinel)
	}
	if flusher != nil {
		flusher.Flush()
	}
}

// lineFlushWriter flushes after every write so the hub sees live progress.
type lineFlushWriter struct {
	w       io.Writer
	flusher http.Flusher
}

func (l *lineFlushWriter) Write(p []byte) (int, error) {
	n, err := l.w.Write(p)
	if l.flusher != nil {
		l.flusher.Flush()
	}
	return n, err
}

// sanitizeLine collapses newlines so an error message cannot masquerade as the
// sentinel or split into multiple log lines.
func sanitizeLine(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\r", " "), "\n", " ")
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}
